version: '3'

services:
  auth-api:
    container_name: postgres-db-auth
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: product
      PGDATA: ./data/postgres
    ports:
      - "15432:5432"
    volumes:
      - /home/tito/volumePostgreSQL_auth:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    container_name: pgadmin-teste-auth
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "francitonio@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "16543:80"
    depends_on:
      - auth-api
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
    
    
